// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	GetAccountByID(ctx context.Context, id string) (Account, error)
}

var _ Querier = (*Queries)(nil)
